import argparse
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Sequence

from .isolation import IsolationConfig, IsolationError, run_isolated


DEFAULT_POLICY_TEMPLATE = """# Sentinel default policy (generated by sentinel-setup)
# Authorization policy source of truth:
# policies/rego/sentinel/authz.rego

policy_integrity:
  tamper_detection: true

judge:
  enabled: true
  provider: "ollama"
  model: "llama-guard3"
  endpoint: "http://localhost:11434/api/generate"
  runtime_judge_threshold: 0.4
  risk_threshold: 0.7
  fail_open: false
  prompt_guard:
    enabled: true
    model: "meta-llama/Llama-Prompt-Guard-2-86M"
    threshold: 0.8
    fail_open: false
  injection_scan:
    enabled: true
    on_detection: "approval"
    max_chars_per_source: 65536
    chunk_chars: 8192
    file_reads:
      enabled: true
      allowlist_paths: []
    network_responses:
      enabled: true
      allowlist_hosts: []
      text_content_types:
        - "text/*"
        - "application/json"
        - "application/*+json"
        - "application/xml"
        - "application/*+xml"

phishing:
  enabled: true
  blocked_tlds: [".xyz", ".top", ".zip"]

network_failsafe:
  socket_connect: true
  allow_private_network: false
  blocked_hosts: []
  blocked_ips: []
  allowed_ips: []

opa:
  enabled: true
  url: "http://127.0.0.1:8181"
  decision_path: "/v1/data/sentinel/authz/decision"
  timeout_ms: 1500
  fail_mode: "deny"
"""


@dataclass(frozen=True)
class SetupConfig:
    workspace: Path
    policy: Path
    image: str
    build_if_missing: bool
    run_smoke_test: bool
    overwrite_policy: bool
    non_interactive: bool


class SetupError(RuntimeError):
    """Raised when setup cannot continue."""


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _prompt_yes_no(question: str, *, default: bool = True) -> bool:
    suffix = "Y/n" if default else "y/N"
    raw = input(f"{question} [{suffix}]: ").strip().lower()
    if not raw:
        return default
    return raw in ("y", "yes")


def _friendly_prereq_error(stage: str, technical_message: str) -> str:
    msg = technical_message.lower()
    if "not found" in msg or "no such file" in msg:
        return (
            f"{stage} failed because Docker is not installed or not available in your terminal PATH. "
            "Install Docker Desktop and restart your terminal, then run sentinel-setup again."
        )
    if "permission denied" in msg:
        return (
            f"{stage} failed due to permission issues when talking to Docker. "
            "Open Docker Desktop once, wait until it is ready, then retry."
        )
    if "cannot connect" in msg or "is the docker daemon running" in msg:
        return (
            f"{stage} failed because Docker Engine is not running. "
            "Start Docker Desktop and wait until it shows 'Engine running', then retry."
        )
    return f"{stage} failed. {technical_message}"


def _run_command(cmd: Sequence[str]) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True)


def _check_docker_binary() -> None:
    docker = shutil.which("docker")
    if docker is None:
        raise SetupError(
            _friendly_prereq_error("Prerequisite check", "Docker binary not found in PATH")
        )


def _check_docker_daemon() -> None:
    result = _run_command(["docker", "info"])
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or "Unknown Docker error"
        raise SetupError(_friendly_prereq_error("Docker health check", detail))


def _check_docker_compose() -> None:
    result = _run_command(["docker", "compose", "version"])
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or "Unknown Compose error"
        raise SetupError(
            _friendly_prereq_error(
                "Docker Compose check",
                f"Compose v2 is not available. {detail}",
            )
        )


def _workspace_rel(repo_root: Path, workspace: Path) -> str:
    try:
        return str(workspace.relative_to(repo_root))
    except ValueError:
        return str(workspace)


def _ensure_workspace(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def _write_policy(path: Path, workspace: Path, overwrite: bool) -> str:
    repo_root = _repo_root()
    workspace_rel = _workspace_rel(repo_root, workspace)
    existed_before = path.exists()

    if existed_before and not overwrite:
        return "kept"

    body = DEFAULT_POLICY_TEMPLATE.format(workspace_rel=workspace_rel)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    return "updated" if existed_before else "created"


def _run_smoke_test(cfg: SetupConfig) -> None:
    iso_cfg = IsolationConfig(
        image=cfg.image,
        workspace=str(cfg.workspace),
        policy=str(cfg.policy),
        network_mode="none",
        build_if_missing=cfg.build_if_missing,
    )
    try:
        result = run_isolated(["python", "-c", "print('sentinel setup check: ok')"], iso_cfg, check=False)
    except IsolationError as exc:
        raise SetupError(
            _friendly_prereq_error(
                "Isolation smoke test",
                str(exc),
            )
        )

    if int(result.returncode) != 0:
        raise SetupError(
            "Isolation smoke test failed. Docker started, but Sentinel could not run a sandboxed test command. "
            "Try again with --build-if-missing, then inspect Docker logs if it still fails."
        )


def _parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Interactive setup wizard for Sentinel Guard."
    )
    parser.add_argument(
        "--workspace",
        default="./sandbox-workspace",
        help="Workspace directory Sentinel will mount in isolation mode.",
    )
    parser.add_argument(
        "--policy",
        default="./sentinel.yaml",
        help="Policy file path to create or reuse.",
    )
    parser.add_argument(
        "--image",
        default="sentinel-guard:local",
        help="Docker image used by sentinel-isolate.",
    )
    parser.add_argument(
        "--build-if-missing",
        action="store_true",
        help="Build image automatically if it does not exist.",
    )
    parser.add_argument(
        "--skip-smoke-test",
        action="store_true",
        help="Skip isolated test run validation.",
    )
    parser.add_argument(
        "--overwrite-policy",
        action="store_true",
        help="Overwrite existing policy file with safe defaults.",
    )
    parser.add_argument(
        "--non-interactive",
        action="store_true",
        help="Run without prompts; uses provided flags/defaults.",
    )
    return parser.parse_args(argv)


def _create_setup_config(args: argparse.Namespace) -> SetupConfig:
    repo_root = _repo_root()
    workspace = (repo_root / args.workspace).resolve() if not Path(args.workspace).is_absolute() else Path(args.workspace).resolve()
    policy = (repo_root / args.policy).resolve() if not Path(args.policy).is_absolute() else Path(args.policy).resolve()

    overwrite_policy = bool(args.overwrite_policy)
    run_smoke_test = not bool(args.skip_smoke_test)

    if not args.non_interactive:
        print("Sentinel setup wizard")
        print("This will check Docker, create safe defaults, and optionally run a test in isolation.")
        if policy.exists() and not args.overwrite_policy:
            overwrite_policy = _prompt_yes_no(
                f"Policy already exists at {policy}. Overwrite with safe defaults?",
                default=False,
            )
        run_smoke_test = _prompt_yes_no("Run isolated smoke test now?", default=True)

    return SetupConfig(
        workspace=workspace,
        policy=policy,
        image=args.image,
        build_if_missing=bool(args.build_if_missing),
        run_smoke_test=run_smoke_test,
        overwrite_policy=overwrite_policy,
        non_interactive=bool(args.non_interactive),
    )


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = _parse_args(argv)
    cfg = _create_setup_config(args)

    try:
        _check_docker_binary()
        _check_docker_daemon()
        _check_docker_compose()

        _ensure_workspace(cfg.workspace)
        policy_status = _write_policy(cfg.policy, cfg.workspace, cfg.overwrite_policy)

        if cfg.run_smoke_test:
            _run_smoke_test(cfg)

        print("\nSetup complete.")
        print(f"- Workspace: {cfg.workspace}")
        print(f"- Policy: {cfg.policy} ({policy_status})")
        print("- Docker: ready")
        if cfg.run_smoke_test:
            print("- Isolation smoke test: passed")
        else:
            print("- Isolation smoke test: skipped")

        print("\nNext command:")
        print("sentinel-isolate --build-if-missing -- python your_agent.py")
        return 0

    except SetupError as exc:
        print(f"Setup could not finish: {exc}")
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
